version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install uv
    - uv run --only-group docs docs build $READTHEDOCS_OUTPUT/html --builder dirhtml

sphinx:
  configuration: docs/conf.py
