name: ✨ Feature Request
description: Suggest a new feature or improvement.
type: ✨ Feature
body:
  - type: dropdown
    attributes:
      label: 🧰 Request Type
      description: |
        Are you requesting a new feature or a new module?
      options:
        - Feature
        - Module
    validations:
      required: true

  - type: input
    attributes:
      label: 🧩 Feature or Module Name
      description: |
        Enter the name for the feature or module (e.g., `#bs.block:get_block`, `bs.health`).
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 Description
      description: |
        Provide a clear explanation of what the feature or module should do and why it's useful.
      placeholder: |
        Examples:
        - Adds support for managing block states more easily.
        - Enhances performance when checking player status.
    validations:
      required: true
