name: 📝 Other
description: Share a suggestion, question, or anything else that doesn’t fit other categories.
body:
  - type: textarea
    attributes:
      label: 💬 Suggestion or Question
      description: |
        Let us know what you'd like to suggest, ask, or discuss:
        - What should be added, improved, or clarified?
        - Include tools, examples, or links if helpful.
      placeholder: |
        Examples:
        - Suggest adding a related tool to the documentation.
        - Ask for clarification on a specific feature.
    validations:
      required: true
