name: ⚙️ Metadata Update

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit:
    name: 🔖 Commit Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Update Metadata
        run: uv run update
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "🛠️ chore: update generated metadata" || echo "No metadata updates"
          git push origin HEAD:${{ github.ref }}
