name: ⚙️ Metadata Update

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  commit:
    name: 🔖 Commit Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Git User
        uses: fregante/setup-git-user@v2
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install Dependencies
        run: pdm install
      - name: Update Metadata
        if: ${{ !startsWith(github.ref_name, 'release/v') }}
        run: pdm run modules update
      - name: Update Metadata for Release
        if: ${{ startsWith(github.ref_name, 'release/v') }}
        run: pdm run modules update --versions
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "⚙️ ci: update generated metadata" || echo "No metadata updates"
          git push origin HEAD:${{ github.ref }}
