name: 🕹️ Release Trigger

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    uses: ./.github/workflows/release-check.yml

  prepare:
    name: 🔖 Create Release PR
    needs: check
    if: ${{ needs.check.outputs.version_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Git User
        uses: fregante/setup-git-user@v2
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install Dependencies
        run: pdm install
      - name: Update Metadata for Release
        run: pdm run modules update --versions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/${{ needs.check.outputs.release_tag }}
          title: |
            🛠️ chore: release ${{ needs.check.outputs.release_name }}
          commit-message: |
            🛠️ chore: release ${{ needs.check.outputs.release_name }}
          delete-branch: true
          sign-commits: true
