name: 🕹️ Release Trigger

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    uses: ./.github/workflows/release-check.yml

  prepare:
    name: 🔖 Create Release PR
    needs: check
    if: ${{ needs.check.outputs.version_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Release ${{ needs.check.outputs.release_name }}
          branch: release/${{ needs.check.outputs.release_tag }}
          delete-branch: true
          sign-commits: true
